### ISSUE TITLE
Strange code in typesetter menu.php

### ISSUE THREAD

**Issue by gtbu** [mahotilo/LinkChecker#2]
You can delete this issue after reading : 
I  have a question because the Typesetter master was scanned  with several tools :
In Menu.php line 180 i see ... $gp_menu_collapse = substr($gp_menu_collapse, $pos + strlen($search)); 

I get the error with php 8.1  (ExecInfo() Fatal Error: Unsupported operand types: string + int )

Do You have an idea why  the + is  used at all ???  

I would have used  
global $pos;  $pos .= (string)(strlen($search)); or :  $pos . '' . (string)(strlen($search)) 

*** or did the author try to add the values of a number-string to an integer ?
like : intval ($var1)  + intval($var3);

( I hope You are not too busy because of the war.....which will hopefully end at least until summer )

**Comment by mahotilo** [comment]
Indeed, a very strange location of the error.
Line [180](https://github.com/Typesetter/Typesetter/blob/a1e7a0bfbc0ac9f38746bcef6af610f137ac4087/include/admin/Menu.php#L180) looks legal.

`$gp_menu_collapse = substr($gp_menu_collapse, $pos + strlen($search))`;

> substr(**string** $string, **int** $offset, ?int $length = **null**): string

`$pos = strpos($gp_menu_collapse, $search); `
So, `$pos` is **int**

> strlen(string $string): int; 

So, `strlen` returns **int**
Thus, we have **int** + **int**, don't we?

Can it be, that problem is related to `$gp_menu_collapse`? Actually, to `$_COOKIE['gp_menu_hide']`? Maybe it isn't a string or undefined?

**Comment by gtbu** [comment]
Unsupported operand types: string + int
 $pos is a string and  strlen($search) is integer. A $var1 = $var2 + 5 should still function. So my proposal is
$pos + intval(strlen($search))) or intval($pos) + intval(strlen($search))) - should be cheedd, which influences it has on the Menu.

(P.S. Your email at bplaced has a problem with google)

**Comment by mahotilo** [comment]
> $pos is a string-variable 

Weird.
It should be `int|false` (https://www.php.net/manual/en/function.strpos)

But if  your solution `intval($pos) ` woks, it will be great.

> P.S. Your email at bplaced has a problem with google

Thx. Have to check it.

**Comment by gtbu** [comment]
We are mixing her something up (public function SetCollapseSettings() ..)
The code of my error was in line 180
$gp_menu_collapse = substr($gp_menu_collapse, $pos + strlen($search));  Here an : intval($pos)  should work.
then in 181
 $pos = strpos($gp_menu_collapse, ']');  can be int or false. 
Line 183 returns 

The other point is strpos in line 175 : $pos = strpos($gp_menu_collapse, $search);
strpos(string $haystack, string $needle, int $offset = 0): int|false
** php 8.0.0 :  strpos Passing an int as needle is no longer supported. 
So $search must be a string 
This code was  left before with return in line 177 

I dont know whether this is worth an issue at github. While i was updating the plugins (under Support) Joshua seems to have been rather 'confused' and he temporarly  inhibited my acess. Typesettercms.com becomes a museum. I dont think he will give it to another person. I have now a 4-core Ubuntu-Vserver with 530Gb and Plesk at Strato.

**Comment by mahotilo** [comment]
I still suspect it is related to $_COOKIE['gp_menu_hide'].

I do not have a possibility to check this. But, what if change
` $gp_menu_collapse =& $_COOKIE['gp_menu_hide'];  `
to 
 `$gp_menu_collapse = 'foo';`?
Will the error persist?

**Comment by gtbu** [comment]
I opened http://localhost/tp53-b4/Admin/Menu with php 8.1.6 
The solution was  	$gp_menu_collapse = substr( $gp_menu_collapse, intval($pos) + intval(strlen($search)) );
Strangely i have to add it to strlen as well....

**Comment by mahotilo** [comment]
Indeed. 
Looks like a kludge.

Nevertheless, can this issue be considered resolved?

**Comment by gtbu** [comment]
This is for my php8-version. If You want to add it to Typesetter-Master - i wont.
But You can close this issue here and delete it.
I hav now still errors like 
*  while (preg_match(static::$whitePattern, $this->buffer, $m, null, $this->count)) {..
* preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated
    in: I:\Xampp8.1.16\xampp\htdocs\tp53-b4\include\thirdparty\ScssPhp\ScssPhp\Parser.php
    on line: 1473
and getting more familiar with php !  Have a nice weekend.
